### ISSUE TITLE
Build fails with AppSync Gradle plugin version 2.6.18

### ISSUE THREAD

**Issue by SudarAbisheck** [awslabs/aws-mobile-appsync-sdk-android#10]
The build is failing during the `afterEvaluate` phase.

```
. . .
09:44:27.476 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Configure project :app'
09:44:27.476 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
09:44:27.476 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Configure build'
09:44:27.478 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
09:44:27.478 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
09:44:27.478 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
09:44:27.478 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Where:
09:44:27.478 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Build file '/Users/*******/******/appsync/AppSyncExperiment2/app/build.gradle' line: 2
09:44:27.478 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
09:44:27.479 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
09:44:27.479 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] A problem occurred evaluating project ':app'.
09:44:27.479 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > com/moowork/gradle/node/NodePlugin
09:44:27.479 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
09:44:27.479 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
09:44:27.479 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]  Run with --scan to get full insights.
09:44:27.479 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
09:44:27.479 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
09:44:27.480 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.GradleScriptException: A problem occurred evaluating project ':app'.
09:44:27.480 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:92)
09:44:27.480 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:199)
09:44:27.480 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
09:44:27.480 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:204)
. . .
```

I think the recent change which made `NodePlugin` as `compileOnly` dependency in gradle is what causing the issue. https://github.com/awslabs/aws-mobile-appsync-sdk-android/blob/a57a80a7f31085115bb1b7479d88dc3d89f994d3/aws-android-sdk-appsync-gradle-plugin/build.gradle#L15

**Comment by SudarAbisheck** [comment]
I tested the plugin locally and changing `compileOnly` to `compile` fixes the issue.
