### ISSUE TITLE
SDK doesn't upload Complex objects to S3 if the input object of a mutation has fields which are of type "S3ObjectInput"

### ISSUE THREAD

**Issue by SudarAbisheck** [awslabs/aws-mobile-appsync-sdk-android#11]
The SDK uploads Complex objects to S3 only if the query document has the text "S3ObjectInput" [[1]]. 

However, the text "S3ObjectInput" will be only present in the query document only if the input object of the mutation is of type "S3ObjectInput". 
```
mutation ($obj: S3ObjectInput!){
  putUser(obj: $obj){
      bucket
      region
      key
  }
}
```
The query document will not have the word "S3ObjectInput" in cases like the following. Here, `UserInput` has another object called `pic` which is of type 'S3ObjectInput`.

```
mutation ($user: UserInput!){
  putUser(user: $user){
    user
    email
    pic {
      bucket
      region
      key
    }
  }
}
```

The `getS3ComplexObject(..)` function checks for these kind of cases recursively [[2]]. However, due to the above issue, this part of the code never gets executed. Also, it checks for "S3ObjectInput" objects only inside a `Map` and doesn't check inside `List`. 

[1]: https://github.com/awslabs/aws-mobile-appsync-sdk-android/blob/a57a80a7f31085115bb1b7479d88dc3d89f994d3/aws-android-sdk-appsync/src/main/java/com/amazonaws/mobileconnectors/appsync/AppSyncComplexObjectsInterceptor.java#L50

[2]: https://github.com/awslabs/aws-mobile-appsync-sdk-android/blob/a57a80a7f31085115bb1b7479d88dc3d89f994d3/aws-android-sdk-appsync/src/main/java/com/amazonaws/mobileconnectors/appsync/AppSyncComplexObjectsInterceptor.java#L84/blob/a57a80a7f31085115bb1b7479d88dc3d89f994d3/aws-android-sdk-appsync/src/main/java/com/amazonaws/mobileconnectors/appsync/AppSyncComplexObjectsInterceptor.java#L84

**Comment by igormatheus22** [comment]
Same problem here.

**Comment by rohandubal** [comment]
Hi @SudarAbisheck 

Thanks for reporting this. You are right, currently the SDK checking in limited ways about determining if there is complex object present in the mutation. We can surely enhance the checking mechanism.

To make sure we add the right checks, could you elaborate what is your use-case currently? Is the 2nd example which you posted in the issue the exact use-case which you have?

Thanks,
Rohan

**Comment by SudarAbisheck** [comment]
I can see that issue hasn't been fixed yet. Still, the SDK just checks the query document for the term `S3ObjectInput`. Some query document need not have this word as part of the query.
```
request.operation.queryDocument().contains("S3ObjectInput")
```
The same issue exists in the iOS SDK as well. https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/45

**Comment by janeshenamazon** [comment]
Issue still exists - Instead of checking the S3ObjectInput string in the document, we should be looping through the input variables, and check if any is `instanceof S3InputObjectInterface`. This will be the more flexible approach.

**Comment by motae99** [comment]
+1

**Comment by cbommas** [comment]
@SudarAbisheck @igormatheus22 @janejjshen @motae99 

Version 2.7.3 of the SDK contains the fixes for this issue. Please upgrade to this version and let us know how you it goes.

**Comment by janejjshen** [comment]
Seems to work out quite nicely! Thanks!

Need the following code when initializing the `AWSAppSyncClient`(small modification from the amplify docs), and I do have to manually find and specify the bucket/key attributes, but overall it saves one upload call which is quite nice!

```
client = AWSAppSyncClient.builder()
                    .context(context)
                    .awsConfiguration(new AWSConfiguration(context))
                    .s3ObjectManager(new S3ObjectManagerImplementation(new AmazonS3Client(AWSMobileClient.getInstance())))
                    .cognitoUserPoolsAuthProvider(new CognitoUserPoolsAuthProvider() {
                        @Override
                        public String getLatestAuthToken() {
                            try {
                                return AWSMobileClient.getInstance().getTokens().getIdToken().getTokenString();
                            } catch (Exception e){
                                Log.e("APPSYNC_ERROR", e.getLocalizedMessage());
                                return e.getLocalizedMessage();
                            }
                        }
                    }).build();
```

Is there an equivalent way to download an S3 object automatically? Or do I still need to use the TransferUtility and call download explicitly?

**Comment by minbi** [comment]
Hi @janejjshen ,

Yes, you will still need to manage the download of the S3 object.

We are closing this issue because there has been confirmation the fix is working. Please feel free to open a new issue if the problem persists. We ask this because closed issues are not actively monitored.

Thanks

**Comment by mopilo** [comment]
I'm really stuck here, after adding this line`.s3ObjectManager(new S3ObjectManagerImplementation(new AmazonS3Client(AWSMobileClient.getInstance())))`. I still get S3 Upload failed.

**Comment by mopilo** [comment]
`com.apollographql.apollo.exception.ApolloException: S3 upload failed.
        at com.amazonaws.mobileconnectors.appsync.AppSyncComplexObjectsInterceptor.interceptAsync(AppSyncComplexObjectsInterceptor.java:70)
        at com.apollographql.apollo.internal.interceptor.RealApolloInterceptorChain.proceedAsync(RealApolloInterceptorChain.java:43)
        at com.amazonaws.mobileconnectors.appsync.InMemoryOfflineMutationObject.execute(InMemoryOfflineMutationObject.java:52)
        at com.amazonaws.mobileconnectors.appsync.InMemoryOfflineMutationManager.processNextMutation(InMemoryOfflineMutationManager.java:63)
        at com.amazonaws.mobileconnectors.appsync.AppSyncOfflineMutationManager.processNextInQueueMutation(AppSyncOfflineMutationManager.java:175)
        at com.amazonaws.mobileconnectors.appsync.AppSyncOfflineMutationInterceptor$QueueUpdateHandler.handleMessage(AppSyncOfflineMutationInterceptor.java:236)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)`
