### ISSUE TITLE
Failed to parse http response, Caused by: java.lang.IllegalStateException: Stack is empty.

### ISSUE THREAD

**Issue by jennytick** [awslabs/aws-mobile-appsync-sdk-android#134]
**Describe the bug**
A batch query which works fine in iOS AppSync SDK fails in Android when one (or more) of the items in the returned list is `null`. This same query works fine if all items are not `null`. Also, testing the query in AppSync console in AWS works fine - returns a list of items which has `null` at indexes of objects which are not present in the data source. So the issue seems to be in AppSync's parsing of the server's response.

**Details**
I've used `amplify` to generate schema and query classes. 
Generated schema of the query which throws an exception when one of the elements in the list is `null`: 
```
{
          "name" : "batchGetItemTotalAnalytics",
          "description" : null
          "args" : [ {
            "name" : "ids",
            "description" : null,
            "type" : {
              "kind" : "NON_NULL",
              "name" : null,
              "ofType" : {
                "kind" : "LIST",
                "name" : null,
                "ofType" : {
                  "kind" : "SCALAR",
                  "name" : "String",
                  "ofType" : null
                }
              }
            },
            "defaultValue" : null
          } ],
          "type" : {
            "kind" : "LIST",
            "name" : null,
            "ofType" : {
              "kind" : "OBJECT",
              "name" : "ItemTotalAnalytics",
              "ofType" : null
            }
          },
          "isDeprecated" : false,
          "deprecationReason" : null
        }
```

Exception stack trace:
```
E/CampaignItemDataService: Failed to parse http response
    com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:143)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.access$100(ApolloParseInterceptor.java:54)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:83)
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:110)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.IllegalStateException: Stack is empty.
        at com.apollographql.apollo.internal.util.SimpleStack.pop(SimpleStack.java:45)
        at com.apollographql.apollo.internal.cache.normalized.ResponseNormalizer.didResolveList(ResponseNormalizer.java:114)
        at com.apollographql.apollo.internal.response.RealResponseReader.readList(RealResponseReader.java:185)
        at com.amazonaws.amplify.generated.graphql.BatchGetItemTotalAnalyticsQuery$Data$Mapper.map(BatchGetItemTotalAnalyticsQuery.java:253)
        at com.amazonaws.amplify.generated.graphql.BatchGetItemTotalAnalyticsQuery$Data$Mapper.map(BatchGetItemTotalAnalyticsQuery.java:248)
        at com.apollographql.apollo.internal.response.OperationResponseParser$1.read(OperationResponseParser.java:112)
        at com.apollographql.apollo.internal.json.ResponseJsonStreamReader.nextObject(ResponseJsonStreamReader.java:103)
        at com.apollographql.apollo.internal.response.OperationResponseParser.parse(OperationResponseParser.java:107)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:129)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.access$100(ApolloParseInterceptor.java:54) 
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:83) 
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:110) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
```

Query construction:
```
 BatchGetItemTotalAnalyticsQuery query = BatchGetItemTotalAnalyticsQuery
                            .builder()
                            .ids(ids)
                            .build();
        GraphQLCall.Callback callback = getCheckCallback(ids, listener);
        appSyncClient.query(query)
                            .responseFetcher(AppSyncResponseFetchers.NETWORK_ONLY)
                            .enqueue(callback);

private GraphQLCall.Callback<BatchGetItemTotalAnalyticsQuery.Data>
    getCheckCallback(final @Nonnull List<String> ids, final CheckListener listener) {
        return new GraphQLCall.Callback<BatchGetItemTotalAnalyticsQuery.Data>() {
            @Override
            public void onResponse(@Nonnull Response<BatchGetItemTotalAnalyticsQuery.Data> response) {
              ....
            }

            @Override
            public void onFailure(@Nonnull ApolloException e) {
             ....
            }
        };
    }
```

Project dependencies:
```
dependencies {
    def aws_version = '2.6.30'
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "com.amazonaws:aws-android-sdk-core:$aws_version"
    implementation "com.amazonaws:aws-android-sdk-s3:$aws_version"
    implementation "com.amazonaws:aws-android-sdk-cognito:$aws_version"
    implementation "com.amazonaws:aws-android-sdk-pinpoint:$aws_version"
    implementation("com.amazonaws:aws-android-sdk-mobile-client:$aws_version@aar") {
        transitive = true
    }
    implementation 'com.amazonaws:aws-android-sdk-appsync:2.7.+'
    ...
}
```

**Comment by minbi** [comment]
Hi @jennytick ,

We'll need to look into this. Thanks for the report.

**Comment by desokroshan** [comment]
We are tracking this in Issue #156. Closing this as duplicate.
