### ISSUE TITLE
App crashes on API level below 21

### ISSUE THREAD

**Issue by hms-tuanpham** [awslabs/aws-mobile-appsync-sdk-android#144]
**Describe the bug**
App crashes on API level 19.
`java.lang.ExceptionInInitializerError
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:296)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:262)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1054)
        at com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient.<init>(AWSAppSyncClient.java:158)
        at com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient.<init>(AWSAppSyncClient.java:73)
        at com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient$Builder.build(AWSAppSyncClient.java:524)
        at net.cloudhms.hmscore.activity.MainActivity.initAws(MainActivity.kt:88)
        at net.cloudhms.hmscore.activity.MainActivity.onCreate(MainActivity.kt:42)
        at android.app.Activity.performCreate(Activity.java:5447)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
        at android.app.ActivityThread.access$800(ActivityThread.java:166)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5590)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 19
        at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
        at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
        at okhttp3.internal.platform.Platform.<clinit>`

**To Reproduce**
Initialize in Activity:
`aws = AWSAppSyncClient.builder().context(applicationContext).awsConfiguration(AWSConfiguration(applicationContext)).build()`

**Expected behavior**
No crash

**Environment(please complete the following information):**
 - com.amazonaws:aws-android-sdk-appsync:2.7.+

**Device Information (please complete the following information):**
 - Device: Samsung Tab E
 - Android Version: 4.4.4

Reffer: https://medium.com/square-corner-blog/okhttp-3-13-requires-android-5-818bb78d07ce

**Comment by desokroshan** [comment]
@hms-tuanpham I am able to run my app my app successfully on API level 19. Please note that AppSync SDK depends on okhttp version 3.8.1 and therefore does not require Android 5.0 and higher. Are you specifying a different version of okhttp for your project ?
