### ISSUE TITLE
Crash with java.lang.NullPointerException: value for name authorization == null

### ISSUE THREAD

**Issue by arok** [awslabs/aws-mobile-appsync-sdk-android#161]
**Describe the bug**
Crash with stacktrace 
```java
Fatal Exception: java.lang.NullPointerException: value for name authorization == null
       at okhttp3.Headers.checkValue(Headers.java:280)
       at okhttp3.Headers$Builder.add(Headers.java:324)
       at okhttp3.Request$Builder.addHeader(Request.java:196)
       at com.amazonaws.mobileconnectors.appsync.sigv4.AppSyncSigV4SignerInterceptor.intercept(AppSyncSigV4SignerInterceptor.java:175)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at com.amazonaws.mobileconnectors.appsync.retry.RetryInterceptor.intercept(RetryInterceptor.java:50)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:210)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)`
```

**To Reproduce**
1. Crash reproduces when there are running AppSync operation (like subscriptions or queries) and user try to log out (call AWSMobileClient.getInstance().signOut()) 

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.7.10

**Device Information (please complete the following information):**
 - Device: Nexus 5
 - Android Version: 6.0.1
 - Specific to simulators:

**Comment by desokroshan** [comment]
Thanks for reporting the issue. Could you please share relevant code snippet?

**Comment by arok** [comment]
@desokroshan There is no code snippet because the issue occurs in random manere. But I found my fault and fixed the issue. The issue was in configuration of `AppSynClient`
The following method shouldn't return null (but in docs I saw example with null)
`.cognitoUserPoolsAuthProvider(() -> {
                        try {
                            return AWSMobileClient.getInstance().getTokens().getIdToken().getTokenString();
                        } catch (Exception e) {
                            e.printStackTrace();
                            return e.getLocalizedMessage();
                        }
                    })`

**Comment by palpatim** [comment]
@arok Glad you were able to resolve your issue. Can you point out where in the docs you saw the misleading code so we can address it?

**Comment by arok** [comment]
@powerful23 for now the docs about authorisation for AppSync looks good (I mean this section https://aws-amplify.github.io/docs/android/api#cognito-user-pools) but when I started to develop my application (about 2 month before) there was code sample with returning `null` in catch block and I just copy and paste the code into my project and this was an issue.
Don't know should the appsync sdk cover this case but I think that it should.
Anyway I think we can close the issue.

**Comment by palpatim** [comment]
Thanks for the update. Closing.
