### ISSUE TITLE
When subscribing, getting - ApolloException: Connection Error Reported

### ISSUE THREAD

**Issue by jishindev** [awslabs/aws-mobile-appsync-sdk-android#211]
**Description**
All subscribe calls through the Appsync(2.10.0) android sdk gives 
`ApolloException: Connection Error Reported`

Here's the full stacktrace - 
```
E/ChatVM$listenToTyping: com.apollographql.apollo.exception.ApolloException: Connection Error Reported
        at com.amazonaws.mobileconnectors.appsync.subscription.RealSubscriptionManager$1.onError(RealSubscriptionManager.java:272)
        at com.amazonaws.mobileconnectors.appsync.subscription.mqtt.MqttSubscriptionClient$1.onFailure(MqttSubscriptionClient.java:101)
        at org.eclipse.paho.android.service.MqttTokenAndroid.notifyFailure(MqttTokenAndroid.java:146)
        at org.eclipse.paho.android.service.MqttAndroidClient.simpleAction(MqttAndroidClient.java:1501)
        at org.eclipse.paho.android.service.MqttAndroidClient.connectAction(MqttAndroidClient.java:1439)
        at org.eclipse.paho.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.java:1368)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.Exception: MqttException (0) - java.io.IOException: WebSocket Response header: Incorrect Sec-WebSocket-Key
        at com.amazonaws.mobileconnectors.appsync.subscription.mqtt.MqttSubscriptionClient$1.onFailure(MqttSubscriptionClient.java:101) 
        at org.eclipse.paho.android.service.MqttTokenAndroid.notifyFailure(MqttTokenAndroid.java:146) 
        at org.eclipse.paho.android.service.MqttAndroidClient.simpleAction(MqttAndroidClient.java:1501) 
        at org.eclipse.paho.android.service.MqttAndroidClient.connectAction(MqttAndroidClient.java:1439) 
        at org.eclipse.paho.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.java:1368) 
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313) 
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: MqttException (0) - java.io.IOException: WebSocket Response header: Incorrect Sec-WebSocket-Key
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:715)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: WebSocket Response header: Incorrect Sec-WebSocket-Key
        at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.receiveHandshakeResponse(WebSocketHandshake.java:165)
        at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.execute(WebSocketHandshake.java:76)
        at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:63)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:701)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Expected behavior**
A successful subscription and real-time updates.

**Environment**
 - AppSync SDK Version: 2.10.0

**Device Information (please complete the following information):**
 - Device: Pixel 3XL 
 - Android Version: Android Q Beta 6

**Comment by btilbrook-nextfaze** [comment]
I'm also seeing this. It seems like the SDK should handle the error, implementing backoff or refreshing authentication as needed.

Any updates on this?

**Comment by systane** [comment]
I'm also seeing this error. But it started to happen just before I updated the eclipse.paho.client.mqttv3 to version 1.2.2. I'm also using sdk-appsync 2.10.0

**Comment by zeroDivider** [comment]
I am still facing the same issue. I am using the newest version of appsync (2.10.0 at this moment) and mqttv3 1.2.0 and I could not update for a _long_ while now because appsync is not compatible with the newest version of mqttv3 (1.2.3).

**Comment by HSin-Tse** [comment]
same issue.  pixel3

**Comment by HSin-Tse** [comment]
its ok just run demo  "aws-mobile-appsync-events-starter-android-master"。
but!  
just add a line 
```
    implementation 'com.amazonaws:aws-android-sdk-iot:2.19.3'
```

```
2020-11-25 22:05:36.192 26784-26784/com.amazonaws.deepdish.postsgraphql E/hcia: Subscription failure
    com.apollographql.apollo.exception.ApolloException: Connection Error Reported
        at com.amazonaws.mobileconnectors.appsync.subscription.RealSubscriptionManager$1.onError(RealSubscriptionManager.java:272)
        at com.amazonaws.mobileconnectors.appsync.subscription.mqtt.MqttSubscriptionClient$1.onFailure(MqttSubscriptionClient.java:101)......
```

**Comment by HSin-Tse** [comment]
```
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    ....
        classpath "com.amazonaws:aws-android-sdk-appsync-gradle-plugin:3.1.2"

```
problem fix

**Comment by poojamat** [comment]
Please add     implementation 'com.amazonaws:aws-android-sdk-iot:2.19.3' to gradle

**Comment by eeatonaws** [comment]
Closing this issue due to inactivity. Please create a new issue if you have additional questions.
