### ISSUE TITLE
MqttSubscriptionClient: connection lost

### ISSUE THREAD

**Issue by turswolm** [awslabs/aws-mobile-appsync-sdk-android#22]
Hi,

I'm facing a problem when using subscriptions with Android SDK. When I start my app subscriptions work well for some time (about 1 min). After this time connection is lost and not established any more. It seams that this happens always when I restart my app but I have not figured out a predictable behavior or why this happens.

With my JS client I don't have this issue. So I tried your sample app https://github.com/aws-samples/aws-mobile-appsync-events-starter-android and I have the same issue.

```
07-09 07:07:50.995 2734-3072/com.amazonaws.deepdish.postsgraphql D/AlarmPingSender: Schedule next alarm at 1531120071095
    Alarm scheule using setExactAndAllowWhileIdle, next: 100
07-09 07:07:51.332 2734-2734/com.amazonaws.deepdish.postsgraphql D/ViewEventActivity: Wrote comment to database
07-09 07:07:51.429 2734-2734/com.amazonaws.deepdish.postsgraphql D/MqttSubscriptionClient: connection lost
07-09 07:07:51.429 2734-2734/com.amazonaws.deepdish.postsgraphql D/ViewEventActivity: Subscription completed
```

I'm using the latest version of this SDK (2.6.21) but also faced the problem with earlier versions.

Thx in advance for your answer.

**Comment by minbi** [comment]
Hi @turswolm ,

The logs show that the subscription is completed which means in the `onCompleted` method you can either choose to allow the subscription to end or restart the subscription.

**Comment by turswolm** [comment]
Thank you for your quick response.

I don't think that it's designed behavior that a subscription ends unexpected after some time and I have to subscribe again in the `onCompleted()` method.  In my opinion a subscription should last until I unsubscribe.

The question is, why the connection is lost again and again and why no reconnect is done. I can see no reason. My app (or even the Android emulator) is connected via Wifi and says in the Wifi.

In `MqttSubscriptionClient` in the `MqttCallback` a `java.io.EOFException` with message `null ` is passed as cause in the `connectionLost()` method.

**Comment by lglossman** [comment]
Same problem here. I have narrowed the problem to Android 8.0 or greater. Also when restarting subscription sometimes it throws a `ConcurrentModificationException`.

**Comment by minbi** [comment]
Hi @lglossman ,

Can you provide a stacktrace for the `ConcurrentModificationException`?

**Comment by lglossman** [comment]
` java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
        at com.amazonaws.mobileconnectors.appsync.subscription.RealSubscriptionManager$1.onError(RealSubscriptionManager.java:193)
        at com.amazonaws.mobileconnectors.appsync.subscription.mqtt.MqttSubscriptionClient$ClientConnectionListener.connectionLost(MqttSubscriptionClient.java:184)
        at org.eclipse.paho.android.service.MqttAndroidClient.connectionLostAction(MqttAndroidClient.java:1469)
        at org.eclipse.paho.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.java:1390)
        at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:311)
        at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:47)
        at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:120)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by lglossman** [comment]
@minbi Is onError a terminal event? I ask this because I need to restart the subscription and I'm not sure if i should be doing that on both onComplete and onError.

**Comment by minbi** [comment]
@lglossman ,
The concurrent modification issue should be fixed with version 2.6.24.
The `onComplete` will signal that the subscription has completed due to cancellation or a connection loss.

**Comment by dabeidl** [comment]
How can I distinguish between the two cases that the subscription has completed due to cancellation or a connection loss?

**Comment by kvasukib** [comment]
@turswolm @lglossman @dabeidl What versions of Paho client and MQTT Service client are you using?

**Comment by dabeidl** [comment]
org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0,
org.eclipse.paho:org.eclipse.paho.android.service:1.1.1
and com.amazonaws:aws-android-sdk-appsync:2.6.25

**Comment by cbommas** [comment]
@turswolm @dabeidl @turswolm 
The latest rev of the SDK (2.6.26) contains a fix for the dropped connections. Can you try it out and let us know how it goes.

**Comment by cbommas** [comment]
@turswolm @dabeidl @lglossman 

Just checking back to see if you are still facing the issues with the new rev of the SDK.
