### ISSUE TITLE
com.amazonaws.internal.keyvaluestore.KeyNotFoundException

### ISSUE THREAD

**Issue by Trupen** [awslabs/aws-mobile-appsync-sdk-android#232]
```java
11-15 19:34:39.884 7188-7228/com.bentolingo E/AWSKeyValueStore: com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: CognitoIdentityProviderCache.rsaKeyStoreAlias
11-15 19:34:40.613 7188-7188/com.bentolingo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bentolingo, PID: 7188
    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter device
        at com.bentolingo.activity.LogInActivity$authenticationHandler$1.onSuccess(LogInActivity.kt)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$6$1.run(CognitoUser.java:810)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5293)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by desokroshan** [comment]
@Trupen Thanks for reaching out. Following is just a log message and does not represent a fatal error as mentioned in https://github.com/aws-amplify/aws-sdk-android/issues/1427: 
```java
11-15 19:34:39.884 7188-7228/com.bentolingo E/AWSKeyValueStore: com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: CognitoIdentityProviderCache.rsaKeyStoreAlias
```

The following stack trace seems to be a problem:

```java
    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter device
        at com.bentolingo.activity.LogInActivity$authenticationHandler$1.onSuccess(LogInActivity.kt)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$6$1.run(CognitoUser.java:810)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5293)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

Can you please share your use case and relevant code snippet for us to help debug this issue.

Thanks!
