### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'com.amazonaws.mobileconnectors.s3.transferutility.TransferObserver com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.upload(java.lang.String, java.io.File, com.amazonaws.services.s3.model.ObjectMetadata)' on a null object reference

### ISSUE THREAD

**Issue by asl0007** [awslabs/aws-mobile-appsync-sdk-android#265]
**Unable to upload image to s3 bucket with the following error**
java.lang.NullPointerException: Attempt to invoke virtual method 'com.amazonaws.mobileconnectors.s3.transferutility.TransferObserver com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.upload(java.lang.String, java.io.File, com.amazonaws.services.s3.model.ObjectMetadata)' on a null object reference

**My code Snippet**
**Main Activity file**

```java
package dcm.example.diagnosis;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.ActivityCompat;
import androidx.core.content.ContextCompat;

import android.Manifest;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.graphics.Bitmap;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.provider.MediaStore;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.Toast;

import com.amazonaws.mobile.client.AWSMobileClient;
import com.amazonaws.mobile.config.AWSConfiguration;
import com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient;
import com.amazonaws.mobileconnectors.appsync.sigv4.CognitoUserPoolsAuthProvider;
import com.amazonaws.mobileconnectors.s3.transferutility.TransferListener;
import com.amazonaws.mobileconnectors.s3.transferutility.TransferObserver;
import com.amazonaws.mobileconnectors.s3.transferutility.TransferState;
import com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility;
import com.amazonaws.services.s3.AmazonS3Client;
import com.amazonaws.services.s3.model.ObjectMetadata;

import java.io.File;

import static com.amazonaws.mobile.client.internal.oauth2.OAuth2Client.TAG;

public class MainActivity extends AppCompatActivity {

    ImageView imageView;
    Button chooseBtn;
    private String photoPath;
    private static final int IMAGE_PICK_CODE = 100 ;
    private static final int PERMISSION_CODE = 101 ;
    private static volatile TransferUtility transferUtility;
    private static volatile AWSAppSyncClient client;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        //VIEWS
        imageView = findViewById(R.id.image_view) ;
        chooseBtn = findViewById(R.id.galleryBtn) ;

        //Handle button click
        chooseBtn.setOnClickListener(new View.OnClickListener()
        {
            @Override
            public void onClick(View v)
            {
                // Check runtime Permission
                if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                    if(checkSelfPermission(Manifest.permission.READ_EXTERNAL_STORAGE) ==
                            PackageManager.PERMISSION_DENIED)
                    {
                        //Permission Not Granted, request it.
                        String[] permissions = {Manifest.permission.READ_EXTERNAL_STORAGE} ;
                        //show popup for runtime application
                        requestPermissions(permissions, PERMISSION_CODE) ;
                    }else{
                        //Permission already Granted
                        pickImageFromGallery();
                    }
                }else{
                    //System OS is less than Marshmellow
                    pickImageFromGallery();
                }
            }
        });

        findViewById(R.id.btnOpenCamera).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (ContextCompat.checkSelfPermission(MainActivity.this,Manifest.permission.CAMERA) != PackageManager.PERMISSION_GRANTED){
                    ActivityCompat.requestPermissions(MainActivity.this,
                            new String[]{
                                    Manifest.permission.CAMERA
                            }, 1);
                }
                Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
                startActivityForResult(intent, 1);
            }
        });
        findViewById(R.id.BtnUpload).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                uploadWithTransferUtility(photoPath);

            }
        });
        findViewById(R.id.recBtn).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

            }
        });
        findViewById(R.id.exitBtn).setOnClickListener(new View.OnClickListener()
        {
            @Override
            public void onClick(View v) {
                //Finish method is used to close all open activities.
                finish();
            }
        });
    }

    public static synchronized void init(final Context context) {

        // ... appsyncClient initialization code ...

        if (client == null) {
            final AWSConfiguration awsConfiguration = new AWSConfiguration(context);
            client = AWSAppSyncClient.builder()
                    .context(context)
                    .awsConfiguration(awsConfiguration)
                    .cognitoUserPoolsAuthProvider(new CognitoUserPoolsAuthProvider() {
                        @Override
                        public String getLatestAuthToken() {
                            try {
                                return AWSMobileClient.getInstance().getTokens().getIdToken().getTokenString();
                            } catch (Exception e){
                                Log.e("APPSYNC_ERROR", e.getLocalizedMessage());
                                return e.getLocalizedMessage();
                            }
                        }
                    }).build();
        }

        if (transferUtility == null) {
            transferUtility = TransferUtility.builder()
                    .context(context)
                    .awsConfiguration(AWSMobileClient.getInstance().getConfiguration())
                    .s3Client(new AmazonS3Client(AWSMobileClient.getInstance()))
                    .build();

        }
    }

    public static synchronized AWSAppSyncClient appSyncClient() {
        return client;
    }


    public static synchronized TransferUtility transferUtility() {
        return transferUtility;
    }

    private void uploadWithTransferUtility(String photoPath) {
        String key = getS3Key(photoPath);
        Log.d(TAG, "Uploading file from " + photoPath + " to " + key);
        ObjectMetadata myObjectMetadata = new ObjectMetadata();
        myObjectMetadata.setContentType("image/png");
        TransferObserver uploadObserver = transferUtility().upload( key, new File(photoPath), myObjectMetadata);
        // Attach a listener to the observer to get state update and progress notifications
        uploadObserver.setTransferListener(new TransferListener() {
            @Override
            public void onStateChanged(int id, TransferState state) {
                if(TransferState.COMPLETED == state){
                    // Handle a completed upload.
                    Log.d(TAG, "Upload is completed. ");
                }
            }

            @Override
            public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
                float percentDonef = ((float) bytesCurrent / (float) bytesTotal) * 100;
                int percentDone = (int)percentDonef;

                Log.d(TAG, "ID:" + id + " bytesCurrent: " + bytesCurrent
                        + " bytesTotal: " + bytesTotal + " " + percentDone + "%");
            }


            @Override
            public void onError(int id, Exception ex) {

                // Handle errors
                Log.e(TAG, "Failed to upload photo. ", ex);
            }
        });

    }

    private String getS3Key(String localPath) {
        //We have read and write ability under the public folder
        return "public/" + new File(localPath).getName();
    }

    private void pickImageFromGallery() {
        //intent to pick image
        Intent intent = new Intent(Intent.ACTION_PICK, MediaStore.Images.Media.EXTERNAL_CONTENT_URI) ;
        intent.setType("image/*") ;
        startActivityForResult(intent, IMAGE_PICK_CODE );
    }
    //Handle result of runtime permission
    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions,
                                           @NonNull int[] grantResults) {
        switch(requestCode) {
            case PERMISSION_CODE:{
                if (grantResults.length >0 && grantResults[0] ==
                        PackageManager.PERMISSION_GRANTED){
                    //permisssion was granted
                    pickImageFromGallery();
                }else{
                    //permission was denied
                    Toast.makeText(this, "Permission Denied...!",
                            Toast.LENGTH_SHORT).show();

                }
            }
        }
    }

    //HANDLE RESULT OF PICKED IMAGE
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if ( requestCode == 1 ){
            Bitmap captureImage = (Bitmap) data.getExtras().get("data");
            imageView.setImageBitmap(captureImage);

        }
        if ( resultCode == RESULT_OK && requestCode == IMAGE_PICK_CODE ) {
            //Set Image to ImageView
            imageView.setImageURI(data.getData());
            filepath(data);
        }
    }

    private void filepath(Intent data) {
        Uri selectedImage = data.getData();
        String[] filePathColumn = {MediaStore.Images.Media.DATA};
        Cursor cursor = getContentResolver().query(selectedImage,
                filePathColumn, null, null, null);
        cursor.moveToFirst();
        int columnIndex = cursor.getColumnIndex(filePathColumn[0]);
        String picturePath = cursor.getString(columnIndex);
        cursor.close();
        // String picturePath contains the path of selected Image
        photoPath = picturePath;
    }
}
```
**Manifest File**
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="dcm.example.diagnosis">
    <!-- Take permission from User -->
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

        <activity android:name=".Splash">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
        <!-- -->
        <service android:name="com.amazonaws.mobileconnectors.s3.transferutility.TransferService" />
    </application>

</manifest>
```
** App build.gradle**

```
apply plugin: 'com.android.application'
/*  */
apply plugin: 'com.amazonaws.appsync'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.3"
    defaultConfig {
        applicationId "dcm.example.diagnosis"
        minSdkVersion 23
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    /*  */
    implementation 'com.amazonaws:aws-android-sdk-appsync:2.8.+'
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0'
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
    // Mobile Client for initializing the SDK
    implementation('com.amazonaws:aws-android-sdk-mobile-client:2.8.+@aar') { transitive = true }
    // Cognito UserPools for SignIn
    implementation('com.amazonaws:aws-android-sdk-auth-userpools:2.8.+@aar') { transitive = true }
    // Sign in UI Library
    implementation('com.amazonaws:aws-android-sdk-auth-ui:2.8.+@aar') { transitive = true }
    //Storage
    implementation 'com.amazonaws:aws-android-sdk-s3:2.7.+'
}
```

**Environment:**
-classpath 'com.amazonaws:aws-android-sdk-appsync-gradle-plugin:2.8.+'
 - AppSync SDK Version: [e.g. 2.6.25]

**Device Information **
 - Device: [Redmi Xiaomi Note 4]
 - Android Version: [e.g. Nougat 7.1.2]

**Complete Error Log**
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dcm.example.diagnosis, PID: 20626
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.amazonaws.mobileconnectors.s3.transferutility.TransferObserver com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.upload(java.lang.String, java.io.File, com.amazonaws.services.s3.model.ObjectMetadata)' on a null object reference
        at dcm.example.diagnosis.MainActivity.uploadWithTransferUtility(MainActivity.java:167)
        at dcm.example.diagnosis.MainActivity.access$200(MainActivity.java:39)
        at dcm.example.diagnosis.MainActivity$3.onClick(MainActivity.java:101)
        at android.view.View.performClick(View.java:5619)
        at android.view.View$PerformClick.run(View.java:22298)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

```
Any help  is appreciated

**Comment by raphkim** [comment]
Hi @asl0007 ,

It appears to me that you are not invoking your `init(Context)` method anywhere, where transfer utility appears to be instantiated. Perhaps you meant to call that method inside your `onCreate()` method?

**Comment by asl0007** [comment]
> 
> 
> Hi @asl0007 ,
> 
> It appears to me that you are not invoking your `init(Context)` method anywhere, where transfer utility appears to be instantiated. Perhaps you meant to call that method inside your `onCreate()` method?

Thank You @raphkim  
 It helped to solve my issue.
