### ISSUE TITLE
Crash: IllegalStateException: please call response.close() - okhttp3

### ISSUE THREAD

**Issue by andrey-chorniy** [awslabs/aws-mobile-appsync-sdk-android#305]
**Description**
When our app got switched to AppSync `v3.0.2` from 3.0.1 the users of our app started experiencing the crash.
We don't see errors like that on `3.0.1` (our app use it since Jan 2020 till May 2020)

```
Fatal Exception: java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
       at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:157)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
       at com.amazonaws.mobileconnectors.appsync.sigv4.AppSyncSigV4SignerInterceptor.intercept(AppSyncSigV4SignerInterceptor.java:173)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
       at com.amazonaws.mobileconnectors.appsync.retry.RetryInterceptor.intercept(RetryInterceptor.java:40)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:194)
       at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**Reproducing**
There are no steps to reproduce, of course, the crash is happening sporadically. Please take a look at the additional context.

**Environment**
 - AppSync SDK Version: 3.0.2

**Device Information**
 - Devices: wide range of
 - Android Version: 6 through 10

**Additional context**
Our application is setting up two instances of `AWSAppSyncClient` in `Application.onCreate()`. 

1. One client is configured with our custom S3ObjectManager which extends from `S3ObjectManagerImplementation` and has the following code (to not retry lost files)

```
class CustomS3ObjectManagerImplementation(s3Client: AmazonS3Client): S3ObjectManagerImplementation(s3Client) {
    override fun upload(s3Object: S3InputObjectInterface) {
        val file = File(s3Object.localUri())
        if (!file.exists() || !file.isFile) {
            throw FileNotFoundException("File ${s3Object.localUri()} does not exist or is not a file")
        }
        super.upload(s3Object)
    }
}
```
This client is also configured with `AWSMobileClient.getInstance()` credentials provider.

2. The second client is configured with `CognitoCachingCredentialsProvider` allowing to submit mutations without prior authentication

Both clients use `AWS_IAM` auth mode.

**Comment by rjuliano** [comment]
I believe this has to do with a change in behavior of the OkHttp client library that was introduced with their `3.13.0` release (I believe we were using OkHttp `3.8.0`). 

Their retry interceptor that is added to the request chain by default, treats `FileNotFoundException` as a non-retryable exception[1], which I guess is the behavior you're looking for. 

The one thing I'm not 100% sure about is whether the OkHttp library used to add their retry interceptor to the request chain by default in the version we were using prior to updating our dependency. Will need to take a deeper look at the code.


[1] https://github.com/square/okhttp/blob/0cc3aefa8ee328409bc6797e501308ba0b3c5e17/okhttp/src/main/kotlin/okhttp3/internal/http/RetryAndFollowUpInterceptor.kt#L169

**Comment by ekmwilson** [comment]
Our application is also seeing this crash sporadically in our prod crash reports (using AppSync `v3.1.0`). Wondering if there is any update?

**Comment by jpignata** [comment]
@ekmwilson Thanks for the report. Are you seeing any patterns / any reproduction criteria?

**Comment by imskmatt** [comment]
@jpignata This appear to happen when we receive a 500 error from a service. This seem to trigger the retry mechanism (com.amazonaws.mobileconnectors.appsync.retry.RetryInterceptor.intercept (RetryInterceptor.java:40)) which contain the bug.

**Comment by andrey-chorniy** [comment]
This crash might have been caused by a combination of two factors
1) someplace in either AppSync or apollographql which doesn't close or prevents closing of the response body
2) switch to the new major 4.x version of okhttp where Transmitter class is throwing the aforementioned error

https://square.github.io/okhttp/interceptors
> A call to `chain.proceed(request)` is a critical part of each interceptor’s implementation. This simple-looking method is where all the HTTP work happens, producing a response to satisfy the request. If `chain.proceed(request)` is being called more than once previous response bodies must be closed.

Consequences of this crash (which affects our app and probably other apps using appsync)
- we can't upgrade to the newer appsync version (because of this crash)
- since v3.0.1 doesn't work with the 6.x version of gradle, we can't upgrade to the latest version of android gradle plugin and gradle
- and thus can't upgrade to the newer versions of other libraries

Could you please let us know if this issue is planned to be worked on?

**Comment by Inshaki** [comment]
Any updates here?

**Comment by rjuliano** [comment]
I spent some time trying to reproduce this without any luck. Is there a specific type of request that triggers this error? I understand it happens sporadically, but does it always happen on mutations or queries for example? Are there any other logs available that may help us see something leading up to the error?

**Comment by ntanduc2288** [comment]
We got the same experience when using V3.1.3

`Fatal Exception: java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
       at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:157)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
       at com.amazonaws.mobileconnectors.appsync.sigv4.AppSyncSigV4SignerInterceptor.intercept(AppSyncSigV4SignerInterceptor.java:173)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
       at com.amazonaws.mobileconnectors.appsync.retry.RetryInterceptor.intercept(RetryInterceptor.java:40)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
       at com.pebblebee.app.repositories.appsync.AWSAppSyncClientProvider.lambda$getInstance$0(AWSAppSyncClientProvider.java:32)
       at com.pebblebee.app.repositories.appsync.-$$Lambda$AWSAppSyncClientProvider$sffqMWgwDPHxB-ybAX89080xD-I.intercept()
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:194)
       at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)`

**Comment by andrey-chorniy** [comment]
> I spent some time trying to reproduce this without any luck. Is there a specific type of request that triggers this error? I understand it happens sporadically, but does it always happen on mutations or queries for example? Are there any other logs available that may help us see something leading up to the error?

@rjuliano, in our app we are only using appsync for mutations. So it for sure happened on mutations. Doesn't mean that it can't happen on queries.

Here are the log lines preceding crash. In short - the mutation was queued, IAM credentials were received (probably before executing the mutation and the app crashed.

```
07-31 15:31:50.278 12946 12007 I AS-AppSyncSaveOps: Mutation CreateEvent succeeded, op id: SOMESTRING, input: {id=SOMESTRING, caseId=SOMESTRING, offenderId=SOMESTRING, time=SOMENUMBER, type=SOMESTRING, location={"accuracy":SOMENUMBER,"coordinates":{"latitude":SOMENUMBER,"longitude":SOMENUMBER}}, agencyId=SOMESTRING}
07-31 15:31:50.289 12946 12007 D InterceptorCallback: Thread:[14076]: onCompleted()
07-31 15:31:50.621 12946 13254 I GeocodeEvtLocWorker: Submitting location update for event [SOMESTRING]: Location(coordinates=Coordinates(latitude=SOMENUMBER, longitude=SOMENUMBER), name=null, address=Address(number=SOMESTRING, street=SOMESTRING, city=SOMESTRING, stateShort=SOMESTRING, state=SOMESTRING, county=SOMESTRING, country=SOMESTRING, postalCode=SOMESTRING, accuracy=null, sublocality=null, streetAddress=null, formattedAddress=SOMESTRING, coordinates=Coordinates(latitude=SOMENUMBER, longitude=SOMENUMBER), id=SOMENUMBER), accuracy=null, geofence=null, time=SOMENUMBER)
07-31 15:31:50.621 12946 13254 D FS-AsyncSaveOperations: Saving records async [EventLocationUpdate(eventId=SOMESTRING, location=Location(coordinates=Coordinates(latitude=SOMENUMBER, longitude=SOMENUMBER), name=null, address=Address(number=SOMESTRING, street=SOMESTRING, city=SOMESTRING, stateShort=SOMESTRING, state=SOMESTRING, county=SOMESTRING, country=SOMESTRING, postalCode=SOMESTRING, accuracy=null, sublocality=null, streetAddress=null, formattedAddress=SOMESTRING, coordinates=Coordinates(latitude=SOMENUMBER, longitude=SOMENUMBER), id=SOMENUMBER), accuracy=null, geofence=null, time=SOMENUMBER), time=SOMENUMBER)]
07-31 15:31:50.734 12946 13501 D AWSMobileClient: Inspecting user state details
07-31 15:31:50.735 12946 13501 I AS-AppSyncSaveOps: Going to save SOMESTRING eventLocation to AppSync {eventId=SOMESTRING, location={"city":"SOMESTRING","coordinates":{"latitude":SOMENUMBER,"longitude":SOMENUMBER},"country":"SOMESTRING","county":"SOMESTRING","formattedAddress":"SOMESTRING","number":"SOMESTRING","postalCode":"SOMESTRING","state":"SOMESTRING","stateShort":"SOMESTRING","street":"SOMESTRING"}, time=SOMENUMBER}
07-31 15:31:50.735 12946 13501 D ApolloClientInterceptor: Associating mutation SOMESTRING_eventLocation with request id SOMESTRING
07-31 15:31:50.748 12946 13501 D AppSyncService: Queued mutation in AppSyncWorker.handler: eventId=SOMESTRING
07-31 15:31:50.752 12946 13501 D DataSyncService: Service already running, skiping
07-31 15:31:50.752 12946 12007 D RetryInterceptor: Retry Interceptor called
07-31 15:31:50.753 12946 12007 D AppSyncSigV4SignerInterceptor: Signer Interceptor called
07-31 15:31:50.831 12946 12007 D AWSMobileClient: Inspecting user state details
07-31 15:31:50.986 12946 12007 D AWSMobileClient: hasFederatedToken: true provider: cognito-idp.us-west-2.amazonaws.com/COGNITO_USER_POOL_ID
07-31 15:31:50.986 12946 12007 D AWSMobileClient: waitForSignIn: userState:SIGNED_IN
07-31 15:31:50.986 12946 12007 D AWSMobileClient: getCredentials: Validated user is signed-in
07-31 15:31:51.476 12946 12007 D RetryInterceptor: Will sleep for 170 ms as per backoff sequence
07-31 15:31:51.647 12946 12007 D AppSyncSigV4SignerInterceptor: Signer Interceptor called
07-31 15:31:51.745 12946 12007 D AWSMobileClient: Inspecting user state details
07-31 15:31:51.911 12946 12007 D AWSMobileClient: hasFederatedToken: true provider: cognito-idp.us-west-2.amazonaws.com/COGNITO_USER_POOL_ID
07-31 15:31:51.911 12946 12007 D AWSMobileClient: waitForSignIn: userState:SIGNED_IN
07-31 15:31:51.911 12946 12007 D AWSMobileClient: getCredentials: Validated user is signed-in
--------- beginning of crash
07-31 15:31:51.984 12946 12007 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
07-31 15:31:51.984 12946 12007 E AndroidRuntime: Process: com.ehawk.repath, PID: 12946
07-31 15:31:51.984 12946 12007 E AndroidRuntime: java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:157)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at com.amazonaws.mobileconnectors.appsync.sigv4.AppSyncSigV4SignerInterceptor.intercept(AppSyncSigV4SignerInterceptor.java:173)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at com.amazonaws.mobileconnectors.appsync.retry.RetryInterceptor.intercept(RetryInterceptor.java:40)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:194)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-31 15:31:51.984 12946 12007 E AndroidRuntime:   at java.lang.Thread.run(Thread.java:919)
```

**Comment by rjuliano** [comment]
The code change that attempts to fix this issue [has been released](https://github.com/awslabs/aws-mobile-appsync-sdk-android/releases/tag/release_v3.1.4)
