### ISSUE TITLE
 java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by myounis97** [awslabs/aws-mobile-appsync-sdk-android#343]
I've updated the android-sdk-appsync from 3.1.1 to 3.1.4 then the following exception thrown 

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/amazonaws/mobileconnectors/appsync/AppSyncSubscriptionCall$StartedCallback;
        at com.amazonaws.mobileconnectors.appsync.WebSocketConnectionManager.notifySubscriptionStarted(WebSocketConnectionManager.java:330)
        at com.amazonaws.mobileconnectors.appsync.WebSocketConnectionManager.processJsonMessage(WebSocketConnectionManager.java:206)
        at com.amazonaws.mobileconnectors.appsync.WebSocketConnectionManager.processMessage(WebSocketConnectionManager.java:188)
        at com.amazonaws.mobileconnectors.appsync.WebSocketConnectionManager.access$400(WebSocketConnectionManager.java:45)
        at com.amazonaws.mobileconnectors.appsync.WebSocketConnectionManager$1.onMessage(WebSocketConnectionManager.java:155)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:280)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:220)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:100)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:240)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.amazonaws.mobileconnectors.appsync.AppSyncSubscriptionCall$StartedCallback" on path: DexPathList[[zip file "/data/app/~~oimI8UdbQlRngGt0Z1Oeug==/uhiveapp.uhive.com.uhive-ZL46EyszY1QjEyhfmE6j6Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~oimI8UdbQlRngGt0Z1Oeug==/uhiveapp.uhive.com.uhive-ZL46EyszY1QjEyhfmE6j6Q==/lib/arm64, /data/app/~~oimI8UdbQlRngGt0Z1Oeug==/uhiveapp.uhive.com.uhive-ZL46EyszY1QjEyhfmE6j6Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.amazonaws.mobileconnectors.appsync.WebSocketConnectionManager.notifySubscriptionStarted(WebSocketConnectionManager.java:330) 
        at com.amazonaws.mobileconnectors.appsync.WebSocketConnectionManager.processJsonMessage(WebSocketConnectionManager.java:206) 
        at com.amazonaws.mobileconnectors.appsync.WebSocketConnectionManager.processMessage(WebSocketConnectionManager.java:188) 
        at com.amazonaws.mobileconnectors.appsync.WebSocketConnectionManager.access$400(WebSocketConnectionManager.java:45) 
        at com.amazonaws.mobileconnectors.appsync.WebSocketConnectionManager$1.onMessage(WebSocketConnectionManager.java:155) 
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:280) 
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:220) 
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:100) 
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:240) 
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170) 
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 

 - AppSync SDK Version: 3.1.4

**Comment by myounis97** [comment]
I forgot to upgrade appsync-gradle-plugin to version 3.1.4
