### ISSUE TITLE
android.net.ConnectivityManager$TooManyRequestsException

### ISSUE THREAD

**Issue by sandipgh19** [awslabs/aws-mobile-appsync-sdk-android#376]
`Caused by android.net.ConnectivityManager$TooManyRequestsException
       at android.net.ConnectivityManager.convertServiceException(ConnectivityManager.java:3226)
       at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3445)
       at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:3759)
       at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:3741)
       at com.amazonaws.mobileconnectors.appsync.ConnectivityWatcher.registerNetworkCallback(ConnectivityWatcher.java:68)
       at com.amazonaws.mobileconnectors.appsync.ConnectivityWatcher.register(ConnectivityWatcher.java:35)
       at com.amazonaws.mobileconnectors.appsync.AppSyncOfflineMutationManager.<init>(AppSyncOfflineMutationManager.java:86)
       at com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient.<init>(AWSAppSyncClient.java:209)
       at com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient.<init>(AWSAppSyncClient.java:69)
       at com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient$Builder.build(AWSAppSyncClient.java:675))`

 - AppSync SDK Version: 3.2.0

**Comment by sandipgh19** [comment]
Any Update on this?

**Comment by sunnyeverestek** [comment]
Still getting in version AppSync SDK Version  3.3.0

**Comment by ekmwilson** [comment]
My team is seeing the same issue in our Crash reporting.

**Comment by tbartley** [comment]
I do not believe this issue to be fixed. We still see it with version 3.3.2 per this comment on the fix: https://github.com/awslabs/aws-mobile-appsync-sdk-android/pull/387#issuecomment-1287619218

**Comment by rovedashcam** [comment]
@tbartley  I am also getting same exception any luck to get this solution even i posted this question here https://stackoverflow.com/questions/75079780/android-net-connectivitymanagertoomanyrequestsexception-in-android-while-networ but still not solution found .

**Comment by CyprienRicque** [comment]
I am facing the same issue using Amplify Datastore

**Comment by rovedashcam** [comment]
Hi ,
I just want to know before explaining this are you using in VLC media
library or any preview thing in your APP?

**Comment by CyprienRicque** [comment]
Hi,
I am only displaying images using coil.compose.AsyncImage from their urls
These images have nothing to do with AWS

**Comment by mahdit8** [comment]
> Hi, I am only displaying images using coil.compose.AsyncImage from their urls These images have nothing to do with AWS

I see the same issue even with Glide. I'm still working on it to see what is the best solution!
