### ISSUE TITLE
App Sync SDK crashing with SQLiteBlobTooBigException 

### ISSUE THREAD

**Issue by IolandaRosa** [awslabs/aws-mobile-appsync-sdk-android#391]
**Describe the bug**
App Sync SDK crashes in AppSyncMutationSqlCacheOperations.fetchAllRecords (AppSyncMutationSqlCacheOperations.java:97) due to SQLiteBlobTooBigException, and the issue seems to be related with memory handling issues. This is only happening on one device in the Play Console.

**To Reproduce**
The crash appears to occur as soon as the user launches the app and the synchronization process begins.

**Expected behavior**
The crash should be handled, and the SDK should log an error message that describes the issue.

**Environment:**
 - AppSync SDK Version: 3.3.1

**Device Information:**
 - Device: Motorola moto z4
 - Android Version: 29 (Android 10)

**Additional context**
I'd like to know if anyone else has experienced this or a similar crash, and I'd like some clarification on what might be causing this (I'm guessing it's related to the size of user data) and how it could be handled in client applications. 

The following is the crash log message:

Caused by: android.database.sqlite.SQLiteBlobTooBigException: 
  at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow (Native Method)
  at android.database.sqlite.SQLiteConnection.executeForCursorWindow (SQLiteConnection.java:942)
  at android.database.sqlite.SQLiteSession.executeForCursorWindow (SQLiteSession.java:838)
  at android.database.sqlite.SQLiteQuery.fillWindow (SQLiteQuery.java:62)
  at android.database.sqlite.SQLiteCursor.fillWindow (SQLiteCursor.java:153)
  at android.database.sqlite.SQLiteCursor.getCount (SQLiteCursor.java:140)
  at android.database.AbstractCursor.moveToPosition (AbstractCursor.java:232)
  at android.database.AbstractCursor.moveToFirst (AbstractCursor.java:271)
  at com.amazonaws.mobileconnectors.appsync.AppSyncMutationSqlCacheOperations.fetchAllRecords (AppSyncMutationSqlCacheOperations.java:97)
  at com.amazonaws.mobileconnectors.appsync.PersistentOfflineMutationManager.fetchPersistentMutationsList (PersistentOfflineMutationManager.java:86)
  at com.amazonaws.mobileconnectors.appsync.PersistentOfflineMutationManager.<init> (PersistentOfflineMutationManager.java:40)
  at com.amazonaws.mobileconnectors.appsync.AppSyncOfflineMutationManager.<init> (AppSyncOfflineMutationManager.java:79)
  at com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient.<init> (AWSAppSyncClient.java:209)
  at com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient.<init> (AWSAppSyncClient.java:69)
  at com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient$Builder.build (AWSAppSyncClient.java:675)

**Comment by mkabore** [comment]
Hello,
I have also encountered this same issue on Samsung Tab Active2, running Android 9.  I am also using the SDK 3.3.1

crash log:
    android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=3
        at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1060)
        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:161)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:149)
        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
        at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:259)
        at com.amazonaws.mobileconnectors.appsync.AppSyncMutationSqlCacheOperations.fetchAllRecords(AppSyncMutationSqlCacheOperations.java:97)
        at com.amazonaws.mobileconnectors.appsync.PersistentOfflineMutationManager.fetchPersistentMutationsList(PersistentOfflineMutationManager.java:86)
        at com.amazonaws.mobileconnectors.appsync.PersistentOfflineMutationManager.<init>(PersistentOfflineMutationManager.java:40)
        at com.amazonaws.mobileconnectors.appsync.AppSyncOfflineMutationManager.<init>(AppSyncOfflineMutationManager.java:79)
        at com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient.<init>(AWSAppSyncClient.java:205)
        at com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient.<init>(AWSAppSyncClient.java:68)
        at com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient$Builder.build(AWSAppSyncClient.java:664)

**Comment by sunnyeverestek** [comment]
Hello,
I have also encountered this same issue on Mi A1, running Android 9. I am also using the SDK 3.3.1

Fatal Exception: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=1
       at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:859)
       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:149)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:137)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
       at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:259)
       at com.amazonaws.mobileconnectors.appsync.AppSyncMutationSqlCacheOperations.fetchAllRecords(AppSyncMutationSqlCacheOperations.java:97)
       at com.amazonaws.mobileconnectors.appsync.PersistentOfflineMutationManager.fetchPersistentMutationsList(PersistentOfflineMutationManager.java:86)
       at com.amazonaws.mobileconnectors.appsync.PersistentOfflineMutationManager.<init>(PersistentOfflineMutationManager.java:40)
       at com.amazonaws.mobileconnectors.appsync.AppSyncOfflineMutationManager.<init>(AppSyncOfflineMutationManager.java:79)
       at com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient.<init>(AWSAppSyncClient.java:209)
       at com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient.<init>(AWSAppSyncClient.java:69)
       at com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient$Builder.build(AWSAppSyncClient.java:675)
       at com.wowe.wowe.network.woweAppSync.WoweAppSyncClient.getKeyInstance(WoweAppSyncClient.java:143)
       at com.wowe.wowe.repository.ApiUserRepository.<init>(ApiUserRepository.java:135)
       at com.wowe.wowe.ui.welocome.WelcomeViewModel.<init>(WelcomeViewModel.java:37)
       at com.wowe.wowe.ui.welocome.WelcomeViewModelFactory.create(WelcomeViewModelFactory.java:22)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:171)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:139)
       at com.wowe.wowe.ui.welocome.WelcomeFragment.onCreate(WelcomeFragment.java:68)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:2981)
       at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:474)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
       at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by IolandaRosa** [comment]
The suggested override of the cursor size solved the issue.

Thanks
