### ISSUE TITLE
Getting nullpoint exception when calling mutation

### ISSUE THREAD

**Issue by Rissmon** [awslabs/aws-mobile-appsync-sdk-android#51]
**Getting nullpoint exception when calling mutation with invalid id**
I am having an issue with AppSync SDL. My application getting crashed when I try to update a value corresponding to an id which is not present in dynamo DB.

Environment:

    AppSync SDK Version: 2.6.26

Device Information:

    Device: Samsung J8, Redmi Note 5 Pro
    Android Version: Marshmallow 6.0, Oreo 8.1

***Since the exception occur inside the SDK i am not able to control this situation**
`
FATAL EXCEPTION: OkHttp Dispatcher
    Process:  PID: 12394
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Set java.util.Map.entrySet()' on a null object reference
        at org.json.JSONObject.<init>(JSONObject.java:132)
        at com.amazonaws.mobileconnectors.appsync.InterceptorCallback.onResponse(AppSyncOfflineMutationInterceptor.java:106)
        at com.apollographql.apollo.internal.interceptor.ApolloCacheInterceptor$1$1.onResponse(ApolloCacheInterceptor.java:102)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:84)
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:110)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by cbommas** [comment]
@Rissmon 

Sorry to hear that you are running into issues. I will investigate this further on my side. Can you provide some more information to help debug this - specifically, can you share your appsync schema and a code snippet from your client.

**Comment by cbommas** [comment]
@Rissmon 
v2.6.27 contains the fix for this issue. Please try with the updated SDK and let us know how it goes.

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue if are still encountering problems.
