### ISSUE TITLE
The app crashes when the sdk is launched

### ISSUE THREAD

**Issue by huforrest** [awslabs/aws-mobile-appsync-sdk-android#62]
**Describe the bug**
The app crashes when the sdk is launched

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.6.28

**Device Information (please complete the following information):**
 - Device: LLD-AL00 UNROOT
 - Android Version: Android 8.0.0, level 26
 - CPU Architecture: aarch64

**Additional context**
The bug only occurs when we use the HUAWEI device.

Here is the crash log:

2018-11-16 16:32:55.123 17910-17910/[Project Name] E/CrashReport: # LAUNCH TIME: 2018-11-16 16:32:47
2018-11-16 16:32:55.123 17910-17910/[Project Name] E/CrashReport: # CRASH TYPE: JAVA_CRASH
2018-11-16 16:32:55.123 17910-17910/[Project Name] E/CrashReport: # CRASH TIME: 2018-11-16 16:32:55
2018-11-16 16:32:55.124 17910-17910/[Project Name] E/CrashReport: # CRASH PROCESS: [Project Name]
2018-11-16 16:32:55.124 17910-17910/[Project Name] E/CrashReport: # CRASH THREAD: main
2018-11-16 16:32:55.124 17910-17910/[Project Name] E/CrashReport: # REPORT ID: a18ab2f7-8c1b-4d37-8046-01e8b65081e5
2018-11-16 16:32:55.124 17910-17910/[Project Name] E/CrashReport: # CRASH DEVICE: LLD-AL00 UNROOT
2018-11-16 16:32:55.125 17910-17910/[Project Name] E/CrashReport: # RUNTIME AVAIL RAM:1477627904 ROM:10434588672 SD:10413617152
2018-11-16 16:32:55.125 17910-17910/[Project Name] E/CrashReport: # RUNTIME TOTAL RAM:2916519936 ROM:25696387072 SD:25675415552
2018-11-16 16:32:55.125 17910-17910/[Project Name] E/CrashReport: # CRASH STACK: 
2018-11-16 16:32:55.125 17910-17910/[Project Name] E/CrashReport: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Out of memory
        at java.lang.Thread.nativeCreate(Native Method)
        at java.lang.Thread.start(Thread.java:753)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:970)
        at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1611)
        at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:342)
        at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
        at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:654)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.start(ClientComms.java:675)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.connect(ClientComms.java:280)
        at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.connect(ConnectActionListener.java:185)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.connect(MqttAsyncClient.java:774)
        at org.eclipse.paho.android.service.MqttConnection.connect(MqttConnection.java:295)
        at org.eclipse.paho.android.service.MqttService.connect(MqttService.java:329)
        at org.eclipse.paho.android.service.MqttAndroidClient.doConnect(MqttAndroidClient.java:467)
        at org.eclipse.paho.android.service.MqttAndroidClient.access$200(MqttAndroidClient.java:76)
        at org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.java:115)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1818)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1847)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7428)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by cbommas** [comment]
@huforrest 

Thanks for providing the stacktrace. Can you also post the contents your logcat and code snippet from your app initialization logic to help debug this further.

**Comment by cbommas** [comment]
@huforrest 

Just checking back to see if you had a chance to get the logcat and code snippets. 

From the stacktrace I see that you are experiencing an OutofMemory error when starting the paho service that manages the MQTT connectivity, but I don't have any way of analyzing it further without the information that I requested.

**Comment by 472574155** [comment]
@cbommas 
AppSync SDK Version: 2.6.28
Device: SO-02J
Android Version: Android 8.0.0, level 26
`    // aws
    implementation 'com.amazonaws:aws-android-sdk-appsync:2.6.+'
    implementation 'com.amazonaws:aws-android-sdk-s3:2.8.+'
    implementation 'com.amazonaws:aws-android-sdk-cognito:2.8.+'
    implementation 'com.amazonaws:aws-android-sdk-mobile-client:2.8.+'
    implementation 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.8.+'
    implementation 'com.amazonaws:aws-android-sdk-sns:2.8.+'

    implementation 'com.amazonaws:aws-android-sdk-core:2.8.+'
    implementation 'com.amazonaws:aws-android-sdk-ddb:2.8.+'
    implementation 'com.google.firebase:firebase-messaging:17.3.4'
    implementation 'com.google.firebase:firebase-core:16.0.4'
    // for Subscriptions
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0'
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'`

When app is running,I have not do any operations. For a while, app crashed. 
[Uploading pthread_create_OOM.pdf…]()

**Comment by 472574155** [comment]
@cbommas 
By the way, com.amazonaws:aws-android-sdk-appsync:2.7.+ Application does not run smoothly.

**Comment by cbommas** [comment]
@472574155 
I am not able to download the pdf file. To reproduce the issue on my side, it would be great if you could post the contents your logcat and code snippet from your app initialization logic to help debug this further.
