### ISSUE TITLE
How do you handle  java.lang.IllegalStateException at RealAppSyncCall.java:350

### ISSUE THREAD

**Issue by olga-dorogan** [awslabs/aws-mobile-appsync-sdk-android#65]
We have a lot of IllegalStateException at RealAppSyncCall.java:350.

After user logs in, our app subscribes to the topic, run some queries and mutations.
First time we faced the issue when the same mutations were processed almost simultaneously, so we got rid of them by cancelling all previously started before starting new one.
But it helps only for this case

How can we handle the exception?

Here is an example of stack trace
```
Fatal Exception: java.lang.IllegalStateException
Expected: TERMINATED, but found [ACTIVE, CANCELED]
com.apollographql.apollo.internal.RealAppSyncCall.b (RealAppSyncCall.java:350)
com.apollographql.apollo.internal.RealAppSyncCall.a (RealAppSyncCall.java:69)
com.apollographql.apollo.internal.RealAppSyncCall$1.onFetch (RealAppSyncCall.java:278)
com.amazonaws.mobileconnectors.appsync.InterceptorCallback.onFetch (AppSyncOfflineMutationInterceptor.java:141)
com.apollographql.apollo.internal.interceptor.ApolloCacheInterceptor$1$1.onFetch (ApolloCacheInterceptor.java:115)
com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onFetch (ApolloParseInterceptor.java:102)
com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1.run (ApolloServerInterceptor.java:91)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
java.lang.Thread.run (Thread.java:764)
```

**Environment:**
 - AppSync SDK Version: 2.6.28

**Device Information:**
 - Device: happens to all devices
 - Android Version: happens to all versions 
 - Specific to simulators: No

**Comment by cbommas** [comment]
@olga-dorogan 

Let me investigate this and get back to you.

**Comment by cbommas** [comment]
@olga-dorogan 

The mutation queue handling logic is intended to be a sequential pipe, executing mutations one at a time. There were, however, synchronization issues and race conditions that were causing the same mutation to be tried more than one thread concurrently, which resulted in this exception.

Version 2.7.1 of the SDK contains synchronization and threading model changes that fixes this issue. 
See https://github.com/awslabs/aws-mobile-appsync-sdk-android/blob/c2dbc52f386d1436833b4e87d3b54af82fecbdb4/aws-android-sdk-appsync-tests/src/androidTest/java/com/amazonaws/mobileconnectors/appsync/AWSAppSyncQueryInstrumentationTest.java#L838 for a test that shows 25 mutations issued in a rapid fire fashion that is then validated for sequential execution.

Please upgrade to v2.7.1 and let us know how you fare.

**Comment by cbommas** [comment]
@olga-dorogan 

Closing as I haven't heard back. Please feel free to post here or create a new thread if still facing issues.

**Comment by DeMoss15** [comment]
@cbommas 
Hello. 

We've caught very similar exception with similar stacktrace on executing a lot of mutations but on *AppSync 2.7.8*:

```
Fatal Exception: java.lang.IllegalStateException: Expected: TERMINATED, but found [ACTIVE, CANCELED]
       at com.apollographql.apollo.internal.RealAppSyncCall.responseCallback(RealAppSyncCall.java:383)
       at com.apollographql.apollo.internal.RealAppSyncCall.access$000(RealAppSyncCall.java:72)
       at com.apollographql.apollo.internal.RealAppSyncCall$1.onResponse(RealAppSyncCall.java:272)
       at com.amazonaws.mobileconnectors.appsync.InterceptorCallback.onResponse(InterceptorCallback.java:127)
       at com.apollographql.apollo.internal.interceptor.ApolloCacheInterceptor$1$1.onResponse(ApolloCacheInterceptor.java:102)
       at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:84)
       at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:110)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by itslonua** [comment]
Fatal Exception: java.lang.IllegalStateException: Expected: TERMINATED, but found [ACTIVE, CANCELED]
       at com.apollographql.apollo.internal.RealAppSyncCall.responseCallback(RealAppSyncCall.java:373)
       at com.apollographql.apollo.internal.RealAppSyncCall.access$000(RealAppSyncCall.java:62)
       at com.apollographql.apollo.internal.RealAppSyncCall$1.onResponse(RealAppSyncCall.java:262)
       at com.amazonaws.mobileconnectors.appsync.InterceptorCallback.onResponse(AppSyncOfflineMutationInterceptor.java:117)
       at com.apollographql.apollo.internal.interceptor.ApolloCacheInterceptor$1$1.onResponse(ApolloCacheInterceptor.java:92)
       at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:71)
       at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:100)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)


**AppSync: 3.3.2**
