### ISSUE TITLE
Getting SocketTimeOutException while executing query

### ISSUE THREAD

**Issue by bhoopendrayash** [awslabs/aws-mobile-appsync-sdk-android#90]
I am getting SocketTimeOutException while executing query, instead in iOS platform it is working without any exception. I have tried to increase timeout as well but it din't help. 

#Graphql Query 
```
query getUserConversationConnectionThroughUser($after: String, $first: Int)
{
    me
    {
        id

        __typename
        conversations(first: $first, after: $after)
        {
            __typename
            nextToken
            userConversations
            {
                __typename
                userId
                conversationId

                associated
                {
                    __typename
                    userId
                }
                conversation
                {
                    __typename
                    id
                    name
                    privacy
                }
            }
        }
    }
}
```

#Code.
```
private void getAllConversationList() {
        if (mAWSAppSyncClient == null) {
            mAWSAppSyncClient = AppHelper.getInstance(getActivity());
        }
        mAWSAppSyncClient.query(GetUserConversationConnectionThroughUserQuery.builder().build())
                .responseFetcher(AppSyncResponseFetchers.CACHE_AND_NETWORK)
                .enqueue(userListCallback);
    }
```
#Callback.
```
    GraphQLCall.Callback<GetUserConversationConnectionThroughUserQuery.Data> userListCallback
            = new GraphQLCall.Callback<GetUserConversationConnectionThroughUserQuery.Data>() {
        @Override
        public void onResponse(@Nonnull Response<GetUserConversationConnectionThroughUserQuery.Data> response) {
            if (response.data() != null) {
                Log.d(TAG, "Check Items: " + response.data().toString());
            }
        }

        @Override
        public void onFailure(@Nonnull ApolloException e) {
            Log.e(TAG, "Failed to make api call", e);
            Log.e(TAG, e.getMessage());
        }
    };
```
#Logs.
MessageFragment: Failed to make api call
```
    com.apollographql.apollo.exception.ApolloNetworkException: Failed to execute http call
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onFailure(ApolloServerInterceptor.java:105)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:215)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
     Caused by: java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664)
        at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:153)
        at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.amazonaws.mobileconnectors.appsync.sigv4.AppSyncSigV4SignerInterceptor.intercept(AppSyncSigV4SignerInterceptor.java:181)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.amazonaws.mobileconnectors.appsync.retry.RetryInterceptor.intercept(RetryInterceptor.java:50)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:760) 
    Failed to execute http call
```
**Environment(please complete the following information):**
 - AppSync SDK Version: [e.g. 2.7.+]
classpath "com.amazonaws:aws-android-sdk-appsync-gradle-plugin:2.7.+"

**Device Information
 - Redmi 4, Moto g4, Samsung S7

**Additional context**
When I try to execute mutation and other queries, it is working as expected.

**Comment by bhoopendrayash** [comment]
- Code snippet for timeout:
ClientConfiguration clientConfiguration = new ClientConfiguration();clientConfiguration.setConnectionTimeout(TIMEOUT);
clientConfiguration.setSocketTimeout(TIMEOUT);
clientConfiguration.setMaxErrorRetry(0);
cognitoUserPool = new CognitoUserPool(context, userPoolId, clientId, clientSecret, clientConfiguration, cognitoRegion);

- Query is running in console as well as in iOS platform.
- I have not tested on simulator, tested only in devices which are mentioned.

**Comment by cbommas** [comment]
@bhoopendrayash 

Thanks for sharing the code snippet. Unfortunately, the timeout that you are setting there doesn't apply to the AppSync call - Within AppSync, it will use OKHttp's default timeout ( which I believe is set to 30 seconds). 

From the log, it does look like a timeout at the OKHTTP level

Couple of follow up items
a) Can you run this on a simulator and see if that works from there
b) Which version of OKHTTP are you using?

**Comment by bhoopendrayash** [comment]
@cbommas 

I am able to run query now in simulator as well as in devices, but I had to make changes in AWSAppSyncClient class (AppSync SDK) for that

OkHttpClient okHttpClient = okHttpClientBuilder
                .addInterceptor(new RetryInterceptor())
                .addInterceptor(appSyncSigV4SignerInterceptor)
                .connectTimeout(60, TimeUnit.SECONDS)//Changes done here
                .readTimeout(60,TimeUnit.SECONDS)//Changes done here
                .build();
				
Is there any way to get OkHttpClient Object at application layer and we can set timeout there only?

**Comment by bhoopendrayash** [comment]
Thanks for you response, I am able to run query now after making changes in okHttpClient.
